---
abstract: 'Simple but non-blocking HTTP client for ClickHouse Database'
author:
  - 'Maxim Motylkov <mmv@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: AnyEvent-ClickHouse
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent: '7.13'
  AnyEvent::HTTP: '2.23'
  Data::Dumper: '2.161'
  Scalar::Util: '1.46'
  Test::HTTP::AnyEvent::Server: '0.013'
  URI: '1.71'
  URI::QueryParam: '1.71'
  perl: v5.10.0
  strict: '0'
  warnings: '0'
version: '0.031'
